# Generated by Django 3.2.5 on 2022-02-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
